name: Trigger auto deployment for containerapp ansalemo-test-ca-deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'log4j2/**'
    - '.github/workflows/ansalemo-test-ca-deployment-AutoDeployTrigger-5d90d263-4ece-4efd-831d-40144d3b6c04.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemocontainerregistry.azurecr.io
          username: ${{ secrets.ANSALEMOTESTCADEPLOYMENT_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOTESTCADEPLOYMENT_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemocontainerregistry.azurecr.io/ansalemo-test-ca-deployment:${{ github.sha }}
          file: ./log4j2/Dockerfile
          context: ./log4j2/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOTESTCADEPLOYMENT_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-test-ca-deployment -g ansalemo-rg --server ansalemocontainerregistry.azurecr.io --username  ${{ secrets.ANSALEMOTESTCADEPLOYMENT_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOTESTCADEPLOYMENT_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-test-ca-deployment -g ansalemo-rg --image ansalemocontainerregistry.azurecr.io/ansalemo-test-ca-deployment:${{ github.sha }}
